### ISSUE TITLE
Implementation of highlighting current search match, rather than blinking

### ISSUE THREAD

**Issue by levouh** [lacygoill/vim-search#2]
This plugin is wonderful, but I often find myself searching and then looking at another split, and then coming back and not being able to easily spot which result I am currently on. I am pretty set on keeping my `Cursor` the way it is, so I was looking to do something more similar to what [vim-searchlight](https://github.com/PeterRincker/vim-searchlight) or [vim-searchhi](https://github.com/qxxxb/vim-searchhi) do in terms of result highlighting.

I understand this is more of a "personal-use" plugin for yourself, but I haven't found anything better that provides everything I want in a single package. I would like to spend the time to implement this myself, but am not really sure where to start so I was looking for some tips from you.

From what I can gather, this plugin works mostly by "wrapping" the common search methods and executing them on the command line via `/` and `?` as necessary. Like you've mentioned in the comments, this allows you to maintain things like `smartcase` settings, etc. I would then imagine some combination of `CmdlineLeave` and `matchadd` would do the job?

If this isn't the case please let me know, but either way I plan to keep on digging in my free time to try to understand how this all works a bit better.

**Comment by levouh** [comment]
I take back what I'd said, it is pretty much as simple as modifying the call the `matchaddpos`, not starting the timer, and then later calling `matchdelete `with the stored `w:blink_id`.

However, I'll leave this open as I'm still curious if you'd go about it any differently :)

**Comment by levouh** [comment]
Closing as this seems to mostly be figured out.

**Comment by lacygoill** [comment]
Sorry for not responding to the issue until now.  When I create a repo, I immediately unstar and unwatch it.  So I was never notified of this issue.

**Comment by levouh** [comment]
No worries at all man. I appreciate the work you've put into this plugin, it is absolutely amazing. The most recent update to support `searchcount()` is incredibly useful as well. The implementation of what I mentioned above is actually quite simple as well. I'm sure there's a better way to do it, but it works so.
